description:
  "HomeGrown is the social network for plant lovers, urban and suburban farmers"
keywords:
  - Gardening
  - Farming
  - Urban Farming
  - Plants
  - flowers
  - fruit trees
  - Social Gardening
  - Plant Map
